# Generated by Django 4.1.2 on 2022-10-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufacturer',
            new_name='Manufacturers',
        ),
    ]
